---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suneel
spec:
  replicas: 10
  selector:
    matchLabels:
      app: suneel
  template:
    metadata:
      labels:
        app: suneel
    spec:
      containers:
      - name: suneel
        image: preeti068/docker-project-august_new2
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: suneel-service
spec:
  selector:
    app: suneel
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
